apiVersion: v1
kind: Service
metadata:
  name: {{ include "goalert.fullname" . }}
  labels:
    {{- include "goalert.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $.Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol | quote }}
      name: {{ .name | quote }}
    {{- end }}
  selector:
    {{- include "goalert.selectorLabels" . | nindent 4 }}
