package config

import (
	"os"
	"strconv"
)

// Token generated by API

var DiscordBotToken string = os.Getenv("DISCORD_BOT_TOKEN")

// Discord chat where alerts will be posted

var DiscordChatID string = os.Getenv("DISCORD_BOT_TOKEN")

// Token generated by BotFather

var TelegramBotToken string = os.Getenv("TELEGRAM_BOT_TOKEN")

// Telegram chat where alerts will be posted

var TelegramChatID, _ = strconv.ParseInt(os.Getenv("TELEGRAM_CHAT_ID"), 10, 64)

// Server port
var Port string = ":" + os.Getenv("SERVICE_PORT")

// Basic Auth user
var Username string = os.Getenv("AUTH_USERNAME")

// Basic Auth password
var Password string = os.Getenv("AUTH_PASSWORD")
