package config

// // Token generated by API

// var DiscordBotToken string = os.Getenv("DISCORD_BOT_TOKEN")

// // Discord chat where alerts will be posted

// var DiscordChatID string = os.Getenv("DISCORD_CHAT_ID")

// // Token generated by BotFather

// var TelegramBotToken string = os.Getenv("TELEGRAM_BOT_TOKEN")

// // Telegram chat where alerts will be posted

// var TelegramChatID, _ = strconv.ParseInt(os.Getenv("TELEGRAM_CHAT_ID"), 10, 64)

// // Server port
// var Port string = ":" + os.Getenv("SERVICE_PORT")

// // Basic Auth user
// var Username string = os.Getenv("AUTH_USERNAME")

// // Basic Auth password
// var Password string = os.Getenv("AUTH_PASSWORD")

// Server
var Port string = ":" + "8080"
var Username string = "test"
var Password string = "test"
var GCPEnabled bool = true
var AZREnabled bool = false
var AWSEnabled bool = false

// Discord
var DiscordBotToken string = ""
var DiscordChatID string = ""

// MSTEams
var TeamsWebhook string = ""

// Slack
var SlackBotToken string = ""
var SlackChatID string = ""

// Telegram
var TelegramBotToken string = ""
var TelegramChatID int64 = 0
