package config

import (
	"os"
	"strconv"
)

// Token generated by BotFather

var BotToken string = os.Getenv("BOT_TOKEN")

// Telegram group where alerts will be posted

var GroupID, _ = strconv.ParseInt(os.Getenv("GROUP_ID"), 10, 64)

// Telegram admin to control the bot

var AdminID, _ = strconv.ParseInt(os.Getenv("ADMIN_ID"), 10, 64)

// Server port

var Port string = ":" + os.Getenv("SERVICE_PORT")

// Basic Auth user

var Username string = os.Getenv("AUTH_USERNAME")

// Basic Auth password

var Password string = os.Getenv("AUTH_PASSWORD")
